
services:
  db:
    image: postgis/postgis:14-3.3
    container_name: postgres-db
    environment:
      POSTGRES_DB: ahaar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nanphaboya
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ahaar
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: nanphaboya

volumes:
  db_data:
